### ISSUE TITLE
SQS Broker throws nullpointer while subscribing

### ISSUE THREAD

**Issue by ghmulti** [micro/go-plugins#129]
In a simple use case: 
```
service := micro.NewService(micro.Name("go.micro.srv.servicename"))
service.Init()
micro.RegisterSubscriber("topicName", service.Server(), listenerFn)
if err := service.Run(); err != nil {
    log.Fatal(err)
}
```
SQS broker expects service broker->Init() function to be called before service.Run() (to setup *sqs.SQS),
 but it happens only if registry option is explicitly set from command line (github.com/go-micro/cmd/cmd.go)

```
if name := ctx.String("registry"); len(name) > 0 || len(ctx.String("registry_address")) > 0 {
...
(*c.opts.Broker).Init(broker.Registry(*c.opts.Registry))
...
}
```
This is not an issue though for nats broker for example, so either sqs broker needs to be fixed or broker.Init() function should always be invoked during service.Init()

**Comment by asim** [comment]
Can you provide the panic so we know what line its failing on?

**Comment by ghmulti** [comment]
Sure

```
goroutine 1 [running]:
github.com/aws/aws-sdk-go/service/sqs.(*SQS).newRequest(0x0, 0xc420198000, 0xcd45c0, 0xc420182010, 0xcadae0, 0xc42000e030, 0x0)
	/gopath/src/github.com/aws/aws-sdk-go/service/sqs/service.go:85 +0x32
github.com/aws/aws-sdk-go/service/sqs.(*SQS).GetQueueUrlRequest(0x0, 0xc420182010, 0x0, 0xc42000e030)
	/gopath/src/github.com/aws/aws-sdk-go/service/sqs/api.go:885 +0x1c9
github.com/aws/aws-sdk-go/service/sqs.(*SQS).GetQueueUrl(0x0, 0xc420182010, 0x0, 0x0, 0x0)
	/gopath/src/github.com/aws/aws-sdk-go/service/sqs/api.go:913 +0x69
github.com/micro/go-plugins/broker/sqs.(*sqsBroker).urlFromQueueName(0xc4200667e0, 0xd63cca, 0x10, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/micro/go-plugins/broker/sqs/sqs.go:270 +0x12e
github.com/micro/go-plugins/broker/sqs.(*sqsBroker).Subscribe(0xc4200667e0, 0xd63cca, 0x10, 0xc4201b0040, 0xc42000e028, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/gopath/src/github.com/micro/go-plugins/broker/sqs/sqs.go:242 +0xbd
github.com/micro/go-micro/server.(*rpcServer).Register(0xc4200a63c0, 0x0, 0x0)
	/gopath/src/github.com/micro/go-micro/server/rpc_server.go:304 +0x1868
github.com/micro/go-micro.(*service).Start(0xc4200ee3c0, 0x0, 0x0)
	/gopath/src/github.com/micro/go-micro/service.go:103 +0x199
github.com/micro/go-micro.(*service).Run(0xc4200ee3c0, 0x0, 0x0)
	/gopath/src/github.com/micro/go-micro/service.go:143 +0x5b
```

**Comment by ghmulti** [comment]
And one more thing regarding SQS, rpcClient by default has Content-Type: "application/octet-stream", so payload generated by rpcClient codec will not be valid from SQS point of view. 
AWS sdk will throw something like 
```
Invalid binary character '#x12' was found in the message body, the set of allowed characters is #x9 | #xA | #xD | [#x20-#xD7FF]
```
The simplest way to fix this - is to base64 encode of payload in some cases(I'll create pull request for that). 

Though I would rather have an additional method on Client interface(something like PublishJson(ctx context.Context, p Publication, opts ...PublishOption) error), like we have for request.
```
NewJsonRequest(service, method string, req interface{}, reqOpts ...RequestOption) Request
NewRequest(service, method string, req interface{}, reqOpts ...RequestOption) Request
```
