### ISSUE TITLE
Broker nsq sometimes got panic when calling Publish()

### ISSUE THREAD

**Issue by hellodudu** [micro/go-plugins#581]
https://github.com/micro/go-plugins/blob/ff11097966f57d55f8fbf254914281a4ccac24f2/broker/nsq/nsq.go#L190

It seems `rand.Intn` will cause panic when calling `Publish` with no producer?

Here's my call stack:

```
WaitGroupWrapper: panic recovered: invalid argument to Intn
call stack: goroutine 2367 [running]:
github.com/yokaiio/yokai_server/utils.(*WaitGroupWrapper).Wrap.func1.1(0xc00008f130)
	/Users/dudu/work/go/src/github.com/yokaiio/yokai_server/utils/wait_group_wrapper.go:19 +0xd1
panic(0x4fd22e0, 0x551c320)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:969 +0x166
math/rand.(*Rand).Intn(0xc00019a180, 0x0, 0x10)
	/usr/local/Cellar/go/1.14.3/libexec/src/math/rand/rand.go:169 +0x9c
math/rand.Intn(...)
	/usr/local/Cellar/go/1.14.3/libexec/src/math/rand/rand.go:337
github.com/micro/go-plugins/broker/nsq.(*nsqBroker).Publish(0xc0002b8180, 0x5284112, 0x13, 0xc0036035a0, 0x0, 0x0, 0x0, 0x30, 0x516f040)
	/Users/dudu/work/go/pkg/mod/github.com/micro/go-plugins@v1.5.1/broker/nsq/nsq.go:189 +0x53
github.com/micro/go-micro/client.(*rpcClient).Publish(0xc000312000, 0x556c7c0, 0xc003621b90, 0x5563380, 0xc003621b30, 0x0, 0x0, 0x0, 0x5563380, 0xc003621b30)
	/Users/dudu/work/go/pkg/mod/github.com/micro/go-micro@v1.18.0/client/rpc_client.go:648 +0x6c3
github.com/micro/go-micro/util/wrapper.(*clientWrapper).Publish(0xc00046d9e0, 0x556c780, 0xc001794cc0, 0x5563380, 0xc003621b30, 0x0, 0x0, 0x0, 0x5563380, 0xc003621b30)
	/Users/dudu/work/go/pkg/mod/github.com/micro/go-micro@v1.18.0/util/wrapper/wrapper.go:46 +0xab
github.com/micro/go-micro.(*publisher).Publish(0xc000318600, 0x556c780, 0xc001794cc0, 0x518e060, 0xc003621ad0, 0x0, 0x0, 0x0, 0x60aba60, 0x556c780)
	/Users/dudu/work/go/pkg/mod/github.com/micro/go-micro@v1.18.0/publisher.go:15 +0xd6
github.com/yokaiio/yokai_server/game.(*PubSub).PubSyncPlayerInfo(0xc0002fc9f0, 0x556c780, 0xc001794cc0, 0xc0007960d8, 0xc001794cc0, 0xc00361c900)
	/Users/dudu/work/go/src/github.com/yokaiio/yokai_server/game/pubsub.go:43 +0x119
github.com/yokaiio/yokai_server/game.(*MsgHandler).handlePublicSyncPlayerInfo.func1(0xc00078a880, 0xc0006bda24, 0x3)
```

**Comment by vtolstov** [comment]
yes, we need to add check for that
